### ISSUE TITLE
split interpolated energies into contributing terms

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#244] opened 2017-06-07 11:38 UTC
is there a reason, why the interpolated energies are only written out for the total energy (even though the header contains further columns with the different contributions (Aniso, Ex, DMI,...))?
It would for example give a lot of insight, if one knows, which terms of the Hamiltonian create the energy barrier. One can see this from the energies of the images, as there the splitting is included, but a splitting of the interpolated values would be even better for plotting purposes.

**Comment by GPMueller** [comment] 2017-06-22 13:50
The problem is that the effective field contributions need to be calculated for the inclinations of the contribution curves to be known at the data-points.
The implementation is a little more involved. However, I will finish it in the near future.

**Comment by GPMueller** [comment] 2018-01-31 09:00
It may make sense to calculate the energy from the scalar product of spin and gradient. Then instead of energy contributions, we would have gradient contributions. Using those, the interpolation of energy contributions could be achieved.

This is related to #311.

**Comment by GPMueller** [comment] 2018-04-17 19:02
The gradient contributions and corresponding energy interpolations could be implemented since PR #395 has been merged.

**Comment by GPMueller** [comment] 2018-05-04 08:39
Actually, the scalar product of spin and gradient is not in general the energy, meaning that this would have to be implemented as an additional functionality.

**Rarely**
- energy contributions
- spin-resolved energy contributions
- spin-resolved total energy
- spin-resolved gradient contributions

**Regularly**
- total energy
- spin-resolved gradient (GNEB)
- spin-resolved gradient contributions (GNEB, if this feature is implemented)
- energy contributions (GNEB, if this feature is implemented)

**Every Iteration**
- spin-resolved gradient (non-MC)
- total energy of single spin (Monte Carlo)

The API and the functions it relies on should be redesigned to support these requirements better. For example, there is no need to re-calculate the energy at every LLG iteration!

**Comment by GPMueller** [comment] 2020-04-02 12:46
This has been implemented with ac3b318785abbcb20f7d56965deaded0cf095929 on the `develop` branch.

**Closed by GPMueller** 2020-04-02 12:46 UTC
Labels: core, enhancement, feature-request
