### ISSUE TITLE
Core: Random failure of physics test for Hamiltonian Pairs

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#378] opened 2017-12-20 15:30 UTC
The values acquired by the functions ```Gradient_FD()``` and ```Gradient()``` may not pass the comparison at "Finite Differences" test case of ```test_physics.cpp``` for a Hamiltonian Pairs.

**Comment by GPMueller** [comment] 2017-12-21 18:19
I have reproduced this on several machines. It only appears sometimes, but it seems that with single-precision the test always fails (at least in the cuda version).

**Comment by GPMueller** [comment] 2018-01-31 22:15
With 8dd8d3501d712869f85fc1795e2109c8ef6a0e91, a bug in the CUDA backend was fixed, which was responsible for illegal memory accesses in `Hamiltonian_Heisenberg_Pairs` and `Hamiltonian_Heisenberg_Neighbours`.
I don't know what the problem with the regular C++ physics test could be - it seems there is no analogous bug there, where e.g. `anisotropy_magnitudes` is accessed with index `ispin` instead of `iani`...

**Comment by GPMueller** [comment] 2018-02-15 13:11
A bug in `Method` was fixed with cc7650acec7b803a0c684eaa5d9a167b6e379fb1. This may be the bug responsible for the random failures, since they do not seem to appear anymore. As these failures were non-deterministic, I cannot be bothered to search for the point they appeared or disappeared.

If the problem re-appears, please feel free to re-open this issue!

**Closed by GPMueller** 2018-02-15 13:11 UTC
Labels: bug, core, unit-test
