### ISSUE TITLE
Error in loading the input.cfg file

### ISSUE THREAD

**Issue by Sayan611** [spirit-code/spirit#615] opened 2022-04-07 21:41 UTC
Hi,
I am getting an error when I am trying to load the input.cfg file in Spirit. I have attached a screenshot regarding this which shows the error message in the middle. I have also attached my input.cgf file which is showing this error.
I will be very grateful if you kindly help me out.
Thanks.
Regards
Sayan Banik

[Input file and error message.zip](https://github.com/spirit-code/spirit/files/8447021/Input.file.and.error.message.zip)

**Comment by MSallermann** [comment] 2022-04-11 10:58
Hey, 
reading in a different config file only works if the number of spins in the new config file is the same as the number of spins currently in the system. I suspect this might be the cause of the issue here. I understand that this behaviour is quite unintuitive...
In practice, I can't think of any time I ever needed this function, though. 

If you want to start the GUI with a certain cfg file I recommend to use command line arguments, like so:
`./spirit -f path/to/myinput.cfg`

**Comment by GPMueller** [comment] 2022-04-26 16:55
See also https://spirit-docs.readthedocs.io/en/latest/core/docs/Features.html and issue #572

**Comment by GPMueller** [comment] 2022-04-30 10:14
@Sayan611 do you have any follow-up questions or can we close this issue?

**Comment by Sayan611** [comment] 2022-04-30 12:19
Dear Mueller
I don't have any questions. You can close this issue. Thanks for your help.

**Closed as completed** 2022-04-30 17:44 UTC
