### ISSUE TITLE
Commits which affected the calculation time

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#389] opened 2018-02-01 12:13 UTC
Our recent tests using bisect showed some commits which affected the calculation time:

d764afe decrease by about 30%

b48e88d decrease by a FACTOR 70
this is partially compensated somewhere between 97f2389 and 369aea7 where a factor of 36 is gained. Between those commits, there is/are one/some buggy one/s which makes bisect impossible.

please check, whether this is due to some severe problems or maybe just due to input file changes etc. :)

**Comment by GPMueller** [comment] 2018-02-01 15:58
Duplicate of #385.

**Closed by GPMueller** 2018-02-01 15:58 UTC
Labels: duplicate
