### ISSUE TITLE
Core Bug: Geometry::calculateDimensionality() gives different (and wrong) results for apple-clang and gcc

### ISSUE THREAD

**Issue by MSallermann** [spirit-code/spirit#423] opened 2018-06-06 08:27 UTC
The `calculateDimensionality()` method of the `Data::Geometry` class gives wrong results for some geometries I tested.
Especially the results are different depending on the compiler I used.

Steps to reproduce:
1. Run spirit with the attached input file (Sc with an additional atom at (0.5, 0.5, 0), N=[10, 10, 1])
2. Look at the result of `calculateDimensionality()` (should be 2)

Result:
- Apple Clang 10.0.0  on macOS 10.13 --> 2
- gcc 7.3.0 on Ubuntu 18.04                   --> 3

Codeversion: current develop branch, 0453420868849f4df7c4b49432eefc7a2f2ee267

Input File:
[input_SC_OB_basis.txt](https://github.com/spirit-code/spirit/files/2075298/input_SC_OB_basis.txt)

Ubuntu Log:
[Log_2018-06-06_10-02-33.txt](https://github.com/spirit-code/spirit/files/2075291/Log_2018-06-06_10-02-33.txt)
Mac Log:
exactly the same

**Comment by GPMueller** [comment] 2018-06-12 12:00
So you're only getting an incorrect result on Ubuntu using gcc, right?

You state the logs are identical, but if the OSX version gives you a 2D geometry, then the log should read something like
```
2018-06-06 10:02:33  [ PARAM ] [IO  ] [--] [--]  Geometry is 2-dimensional
```
instead of
```
2018-06-06 10:02:33  [ PARAM ] [IO  ] [--] [--]  Geometry is 3-dimensional
```

Did you investigate what the problem might be, i.e. which part exactly seems to fail? I cannot tell where it might go wrong from looking at the code and I cannot reproduce the problem on my machines.

**Comment by MSallermann** [comment] 2018-06-12 12:12
Yes only on Ubuntu. And you are right the MacOS Log is different in that regard.
[Log_2018-06-06_10-02-43.txt](https://github.com/spirit-code/spirit/files/2093905/Log_2018-06-06_10-02-43.txt)
I did not investigate at all yet, but I can do so later this week of course.

**Comment by GPMueller** [comment] 2018-10-29 10:50
It seemed this was a precision problem when `float` was used for `scalar`.
Tried to fix with 40fa6f65d3f1b10d345e4d67d28d1f5270c3fa5f, but the issue remains.

**Comment by GPMueller** [comment] 2020-05-18 10:48
Might this for some reason have been fixed by 5ca616a7771872170ce3771aed13138f91ad8597?

**Comment by GPMueller** [comment] 2020-12-22 23:48
This could now also be related to

https://github.com/spirit-code/spirit/blob/3865ae33d8a1c900ce4a31b3c71fbae5f8d1c4b7/core/src/data/Geometry.cpp#L247-L252

and

https://github.com/spirit-code/spirit/blob/3865ae33d8a1c900ce4a31b3c71fbae5f8d1c4b7/core/src/data/Geometry.cpp#L322-L327

which seem to have been introduced with commit [482e16bb](https://github.com/spirit-code/spirit/commit/482e16bb709ed895da2d5cf0e5696662db21e99d#diff-47b32142c6ab90a390d8a89d0fc3d926b037c86e3c27890e9b7971892c04f80c)?

**Comment by GPMueller** [comment] 2021-11-15 20:02
I also recently made small bugfixes,

https://github.com/spirit-code/spirit/commit/fdd532d56efa9305da1411e48620cb623b440289#diff-50ef1a1d730815bf9fb1b17132158740e085d34f9b19f222743a4a35aae5578eL144-R144

and

https://github.com/spirit-code/spirit/commit/a1852fef63f1defcc3661a82c92727318b125dff#diff-47b32142c6ab90a390d8a89d0fc3d926b037c86e3c27890e9b7971892c04f80cL304-R319

in geometry-related code. Together with the removal of some platform-dependent behaviour, the bug _might_ be resolved by now...

In particular (I am not sure _when_), the binary `&` operators have been replaced by the appropriate `&&`:
https://github.com/spirit-code/spirit/blob/a1852fef63f1defcc3661a82c92727318b125dff/core/src/data/Geometry.cpp#L256-L261

**Comment by GPMueller** [comment] 2021-11-17 19:55
I can not reproduce this image on
 - Windows 10, built with clang 12.0.1
 - Windows 10, built with msvc 19.29 (2019)
 - Ubuntu 20.04, built with gcc 9.3.0
 - macOS 11.6, built with apple-clang 13.0.0

@MSallermann can you still reproduce the problem?

**Comment by MSallermann** [comment] 2021-11-18 10:55
It seems to be fixed, cant reproduce it either.

**Closed** 2021-11-25 20:47 UTC
Labels: bug, core
