### ISSUE TITLE
Program crashes when using LLG on loaded spin chain configurations

### ISSUE THREAD

**Issue by JHagemeister** [spirit-code/spirit#287] opened 2017-08-03 08:50 UTC
With Version v1.6.1 - After loading a previously stored spin chain configuration, I go to the spin configuration with the largest index and try to run LLG, the program is likely to crash.

**Comment by GPMueller** [comment] 2017-08-09 13:07
Please attach a Log-file (of a run where this happened) to this issue. Make sure to have set
```Python
### Save the log as a file
log_to_file    1
### Save messages up to (including) log_file_level
log_file_level 6
```
in your input file.

**Comment by GPMueller** [comment] 2017-09-04 12:14
Closing since we cannot reproduce this.
Please re-open this issue if you encounter this problem again on the newest version on the `develop` branch and attach the mentioned info.

**Closed by GPMueller** 2017-09-04 12:14 UTC
Labels: bug
