### ISSUE TITLE
feature-request: adjusting the lattice dimensions on-the-fly

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#212] opened 2017-05-15 12:12 UTC
It might be useful, to make the lattice dimensions adjustable on the fly by adding/deleting a given number of rows in each direction without changing the other parts of the lattice. with this, is would be easier to analyze the effect of boundary conditions and lattice dimensions on a structure.

if one adds rows, one might have to think about how and where to initialize the new ones. 
My suggestion: 
either
- ferromagnet in a definable direction
- copy of the neighboring already existing row
and
- define number of rows to be added on both sides of each direction
- add a "centered" check box which averages when activated automatically the two input values to add the same amount of rows in each direction

**Comment by GPMueller** [comment] 2017-05-15 12:24
I would say this is a duplicate of #102 (and related to #104).

**Closed** 2017-05-15 12:30 UTC
Labels: core, duplicate, feature-request
